Models/Category.cs
namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MovieApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public Movie Movie { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CategoryApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieApp.Data;
using MovieApp.Models;


namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;
            if(id!= null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }
            return View(movies);
        }

        public IActionResult Details(int id)
        { 
            return View(MovieRepository.GetById(id));
        }
        

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            // TODO: Your code here
            return View();
        }

        public IActionResult Details()
        {
            // TODO: Your code here
            return View();
        }
        
        public IActionResult list()
        {
            // TODO: Your code here
            return View();
        }
        
        
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using CategoryApp.Data;
using Microsoft.AspNetCore.Mvc;


namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
       
        }    
    }
}

Views/Home/Details.cshtml
@model Movie

<div class="row">
    <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        <div class="card mb-4">
            <div class="row no-gutter">
                <div class="col-md-3">
                    <img src="~/images/@Model.ImageUrl" alt="@Model.Description" class="card-img">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">@Model.Name</h5>
                        <p class="card-text"> @Html.Raw(@Model.Description)</p>
                        <p class="card-text">
                            <small class="text-muted">3 days ago</small>
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_movies",Model)
    </div>
</div>

Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach (var item in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/images/@item.ImageUrl" alt="@item.Description" class="card-img">
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="/home/details/@item.Id">@item.Name</a>
                    </h5>
                    <p class="card-text">@item.ShortDescription</p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
}

Views/Movie/Details.cshtml
<div class="text-center">
    <h1 class="display-4">Movie/Details</h1>
</div>

Views/Movie/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Movie/Index</h1>
</div>

Views/Movie/List.cshtml
<div class="text-center">
    <h1 class="display-4">Movie/List</h1>
</div>

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">

    <a href="/"
        class="list-group-item list-group-item-action active">Tüm Kategoriler
    </a>

    @foreach (var item in Model)
    {
        <a asp-controller = "Home" asp-action = "Index" asp-route-id = "@item.Id" 
        class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == item.Id.ToString()?" active ":"")">@item.Name
        </a>
    }
    
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
       @Html.Partial("_navbar");
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       @Html.Partial("_footer")
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_footer.cshtml
<div class="container">
    &copy; 2021 - MovieApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

Views/Shared/_menu.cshtml
@model IEnumerable<Category>

<div class="list-group">

    @foreach (var item in Model)
    {
        <a href="#" class="list-group-item list-group-item-action active">@item.Name</a>
    }
    
</div>

Views/Shared/_navbar.cshtml
 <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieApp</a>

                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>